---
- name: Prepare all TravelMemory servers
  hosts: all
  become: true
  roles:
    - role: common

- name: Configure the private MongoDB server
  hosts: database
  become: true
  roles:
    - role: mongodb

- name: Deploy the TravelMemory web application
  hosts: web
  become: true
  roles:
    - role: web
