---
vault_mongodb_admin_username: travelmemoryAdmin
vault_mongodb_admin_password: CHANGE_ME_WITH_A_LONG_RANDOM_PASSWORD
vault_mongodb_app_username: travelmemoryApp
vault_mongodb_app_password: CHANGE_ME_WITH_A_DIFFERENT_LONG_RANDOM_PASSWORD
